'use strict';
import type { Metadata } from "next";
import Script from "next/script";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Default Title",
    template: "%s | WebApp"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body>
    <Navbar/>
    <main className="text-xl container mx-auto px-4 mt-3">
      {children}
    </main>
    <Script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></Script>
    </body>
    </html>
  );
}
